name: topstyle
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  provider: ^3.1.0
  location: ^2.3.5
  google_maps_flutter: ^0.5.21
  http: ^0.12.0+2
  share: ^0.6.3+5
  path: ^1.6.4
  connectivity: ^0.4.6+2
  geolocator: ^5.1.5
  flutter_svg: ^0.14.4
  webview_flutter: ^0.3.17
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6+1
  flutter_webview_plugin: ^0.3.10+1
  cached_network_image: ^2.0.0
#  rate_my_app: ^0.5.0+3








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpeg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon_adaptive.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/cart.png
    - assets/icons/product_recived.png
    - assets/icons/call.png
    - assets/icons/whats.png
    - assets/icons/email.png
    - assets/icons/headphone.png
    - assets/icons/visa.png
    - assets/icons/master.png
    - assets/icons/amex.png
    - assets/icons/mada.png
    - assets/icons/complete_order.png
    - assets/icons/makeup.png
    - assets/icons/device.png
    - assets/icons/care.png
    - assets/icons/lensess.png
    - assets/icons/nails.png
    - assets/icons/perfume.png
    - assets/icons/cash.svg
    - assets/icons/orignal.svg
    - assets/icons/delivary.svg
    - assets/icons/on_the_way.png
    - assets/icons/ksa_flag.png
    - assets/icons/uae_flag.png
    - assets/icons/kw_flag.png
    - assets/icons/apple_pay.png
    - assets/icons/lock.png
    - assets/icons/top_rated.png
    - assets/icons/rm_keyboard.png
    - assets/icons/most_recent.png
    - assets/icons/privacy.svg
    - assets/images/icon.jpeg
    - assets/images/profile.png
    - assets/images/logo.jpg
    - assets/images/antenna.png
    - assets/images/icon_adaptive.png
    - assets/images/splash.jpg
    - assets/lang/en.json
    - assets/lang/ar.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 700
    - family: tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
